// <auto-generated />
namespace API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Prueba20170520 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prueba20170520));
        
        string IMigrationMetadata.Id
        {
            get { return "201705210519512_Prueba20170520"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
