// <auto-generated />
namespace API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _201705141 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201705141));
        
        string IMigrationMetadata.Id
        {
            get { return "201705140519293_20170514.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
